### ISSUE TITLE
Investigate CI failures

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#58] opened 2017-02-07 18:49 UTC
As a developer, I'd like to investigate and fix CI failures for the apps.

- [x] file  - Artem
- [x] gemfire  - Artem
- [x] http  
- [x] jms  - Gary
- [x] load-generator  - Thomas
- [x] loggregator - Soby
- [x] mail  - Artem
- [x] mongodb  
- [x] rabbit  - Soby
- [x] s3  - Artem
- [x] sftp - Gary 
- [x] syslog  - Gary
- [x] tcp  - Gary
- [x] tcp-client  - Gary
- [x] time  - Soby
- [x] trigger  - Soby
- [x] triggertask  - Thomas
- [x] twitterstream - Soby
- [x] bridge - Soby
- [x] filter - Soby
- [x] groovy-filter
- [x] groovy-transform - Soby
- [x] httpclient - Gary
- [x] pmml - Artem
- [x] scriptable-transform
- [x] splitter
- [x] aggregate-counter - Artem
- [x] counter - Artem
- [x] field-value-counter
- [x] ftp
- [x] gpfdist
- [x] hdfs (Thomas)
- [x] hdfs-dataset (Thomas)
- [x] jdbc (Thomas)
- [x] log - Soby
- [x] rabbit - Soby
- [x] redis-pubsub - Soby
- [x] router
- [x] task-launcher-local - Thomas
- [x] task-launcher-yarn
- [x] task-launcher-cloudfoundry - Thomas
- [x] tasklaunchrequest-transform - Artem
- [x] throughput
- [x] websocket - Artem
- [x] cassandra
- [x] header-enricher
- [x] transform - Soby

**Comment by artembilan** [comment] 2017-02-09 20:18
I guess the issue is ready to be closed finally 😄

**Comment by sobychacko** [comment] 2017-02-09 20:31
Closing the issue.

**Closed as completed by sobychacko** 2017-02-09 20:31 UTC
